# .github/workflows/ci.yml
name: CI Workflow - Python

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger when PR is made to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9  # Use Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          pytest  # Run pytest to check the tests
