name: QA Check Label Removal

on:
  pull_request:
    types: [unlabeled]

jobs:
  qa-label-remove-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check label removal and update QA status
        run: |
          if [[ "${{ github.event.label.name }}" == "qa-passed" ]]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                    "state": "pending",
                    "description": "Waiting for QA review",
                    "context": "QA Check"
                  }' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}
          fi
