name: QA Check Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  qa-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set QA check to pending
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "state": "pending",
                  "description": "Waiting for QA review",
                  "context": "QA Check"
                }' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}
